// src/utils/cryptoVault.js

// Utility functions for Hex and Base64 conversions
const hexToBuffer = (hex) => new Uint8Array(hex.match(/.{1,2}/g).map(byte => parseInt(byte, 16)));
const bufferToHex = (buffer) => Array.from(new Uint8Array(buffer)).map(b => b.toString(16).padStart(2, '0')).join('');
const base64ToBuffer = (b64) => Uint8Array.from(atob(b64), c => c.charCodeAt(0));
const bufferToBase64 = (buffer) => btoa(String.fromCharCode(...new Uint8Array(buffer)));

// Derives an AES-GCM key from the provided password
async function getKey(password, salt) {
    const enc = new TextEncoder();
    const keyMaterial = await crypto.subtle.importKey(
        "raw",
        enc.encode(password),
        "PBKDF2",
        false,
        ["deriveKey"]
    );
    return crypto.subtle.deriveKey(
        {
            name: "PBKDF2",
            salt: salt,
            iterations: 100000,
            hash: "SHA-256"
        },
        keyMaterial,
        { name: "AES-GCM", length: 256 },
        false,
        ["encrypt", "decrypt"]
    );
}

export async function encryptVault(data, password) {
    try {
        const salt = crypto.getRandomValues(new Uint8Array(16));
        const iv = crypto.getRandomValues(new Uint8Array(12));
        const key = await getKey(password, salt);
        
        const enc = new TextEncoder();
        const encodedData = enc.encode(JSON.stringify(data));
        
        const encryptedContent = await crypto.subtle.encrypt(
            { name: "AES-GCM", iv: iv },
            key,
            encodedData
        );

        // Match the exact format from your migration.html
        return {
            version: 1,
            salt: bufferToHex(salt),
            iv: bufferToHex(iv),
            ciphertext: bufferToBase64(encryptedContent)
        };
    } catch (e) {
        console.error("Encryption failed:", e);
        throw e;
    }
}

export async function decryptVault(encryptedPackage, password) {
    try {
        let salt, iv, encryptedData;

        // Check if this is the format generated by your migration tool
        if (encryptedPackage.version === 1 || encryptedPackage.ciphertext) {
            salt = hexToBuffer(encryptedPackage.salt);
            iv = hexToBuffer(encryptedPackage.iv);
            encryptedData = base64ToBuffer(encryptedPackage.ciphertext);
        } else {
            // Fallback for older pure base64 structures
            salt = base64ToBuffer(encryptedPackage.salt);
            iv = base64ToBuffer(encryptedPackage.iv);
            encryptedData = base64ToBuffer(encryptedPackage.data);
        }
        
        const key = await getKey(password, salt);
        
        const decryptedContent = await crypto.subtle.decrypt(
            { name: "AES-GCM", iv: iv },
            key,
            encryptedData
        );
        
        const dec = new TextDecoder();
        return JSON.parse(dec.decode(decryptedContent));
    } catch (e) {
        console.error("Decryption failed:", e);
        throw new Error("Invalid password or corrupt vault");
    }
}
